### ISSUE TITLE
Incorrect image name in deployment.yaml

### ISSUE THREAD

**Issue by jianhang33** [gardener/oidc-webhook-authenticator#114]
**What happened**: Failed to deploy the application to kubernetes due to "ErrImagePull"

**What you expected to happen**: the application to be deployed

**How to reproduce it (as minimally and precisely as possible)**: use the file at https://github.com/gardener/oidc-webhook-authenticator/blob/master/config/samples/deployment.yaml to deploy

**Anything else we need to know**: The image name there is oidc-webhook-authenticator:latest, and it didn't work for me. I then replace with eu.gcr.io/gardener-project/gardener/oidc-webhook-authenticator:latest, and then it worked.

**Environment**: Linux, kubernetes

**Comment by jianhang33** [comment]
Here are events I saw when describing the pod

```
  Normal   Pulling    5m28s (x4 over 6m56s)  kubelet            Pulling image "oidc-webhook-authenticator:latest"
  Warning  Failed     5m27s (x4 over 6m56s)  kubelet            Failed to pull image "oidc-webhook-authenticator:latest": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/oidc-webhook-authenticator:latest": failed to resolve reference "docker.io/library/oidc-webhook-authenticator:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
  Warning  Failed     5m27s (x4 over 6m56s)  kubelet            Error: ErrImagePull
  Warning  Failed     5m16s (x6 over 6m55s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    115s (x21 over 6m55s)  kubelet            Back-off pulling image "oidc-webhook-authenticator:latest"

```

**Comment by dimityrmirchev** [comment]
Please use the helm chart https://github.com/gardener/oidc-webhook-authenticator/tree/master/charts/oidc-webhook-authenticator in order to install the webhook authenticator. The deployment you linked is only used in a local dev setup.

**Comment by jianhang33** [comment]
Thanks for the pointer. However, I'd love to see the README.md to include general deployment instructions and then provide local deployment as an example.

**Comment by dimityrmirchev** [comment]
I opened an issue to track the progress on enhancing the documentation w.r.t. deployments https://github.com/gardener/oidc-webhook-authenticator/issues/115
