### ISSUE TITLE
Helm charts should support setting concrete ClusterIP for OWA Service

### ISSUE THREAD

**Issue by dimityrmirchev** [gardener/oidc-webhook-authenticator#116]
**What would you like to be added**:
Helm charts should support setting concrete `ClusterIP` for OWA Service.

**Why is this needed**:
The `kube-apiserver` cannot use in-cluster DNS. It will be easier to configure the `kube-apiserver` if the IP can be explicitly set.

**Comment by angelbarrera92** [comment]
#117 this should solve the issue
