### ISSUE TITLE
Failed to authenticate: "x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by jianhang33** [gardener/oidc-webhook-authenticator#120]
**What happened**:
I generated self-signed certificates using openssl, ca.crt/key, server.crt/key, client.crt/key.
on gardener webhook authenticator side, I created two files tls.crt, which includes server.crt followed by ca.crt, and tls.key, which includes server.key
on kube-apiserver, I started the server with additional argument "authentication-token-webhook-config-file" set, and in the config file "insecure-skip-tls-verify" is set to false, and "certificate-authority" points to the same ca.crt mentioned above. client-certificate and client-key point to client.crt and client.key.

**What you expected to happen**:
authentication successful.

However, authentication failed, and I saw error messages in the log

```
"Unable to authenticate the request" err="[x509: certificate signed by unknown authority, verifying certificate SN=348160067065046693534333205386337215596368073097, SKID=, AKID= failed: x509: certificate signed by unknown authority]"
```

**How to reproduce it (as minimally and precisely as possible)**:
Use openssl to generate ca.crt/key, server.crt/key, client.crt/key. When generating server.crt, I used the IP address used by the kubernetes service for the gardener webhook authenticator as CN.

**Anything else we need to know**:
Earlier in the log, I saw the following message
```
"Loaded serving cert" certName="serving-cert::/var/run/certs/tls.crt::/var/run/certs/tls.key" certDetail="\"108.88.148.88\" 
OIDC: No x509 certificates provided, will use host's root CA set
```
**Environment**:
kubernetes deployed on linux machine.

**Comment by jianhang33** [comment]
I couldn't find any docs related to certificates and where the ca.crt to be stored or somehow passed to the server.

**Comment by dimityrmirchev** [comment]
```
"Unable to authenticate the request" err="[x509: certificate signed by unknown authority, verifying certificate SN=348160067065046693534333205386337215596368073097, SKID=, AKID= failed: x509: certificate signed by unknown authority]"
```
Was this log extracted from the oidc webhook logs?

Once the webhook receives a request it tries to authenticate and authorize it against the kube-apiserver. In this case you provided a client.crt/key that were signed with the oidc webhook CA. In order for this to work you need to use client cert signed by the kube-apiserver's CA or omit the authentication (if no credentials are provided in the kubeconfig the webhook will authenticate the caller as anonymous). Then you can also skip authorization for different routes by setting them [here](https://github.com/gardener/oidc-webhook-authenticator/blob/e0b023fd994d76c88aefc07db60f1cb20f282a14/charts/oidc-webhook-authenticator/values.yaml#L66).

```
OIDC: No x509 certificates provided, will use host's root CA set
```
This is a normal log and it means that you have an openidconnect resource in the cluster without a `caBundle` and the host's root CA set will be used in order to contact the identity provider.

**Comment by jianhang33** [comment]
Thanks for you reply. Yes, It was from gardener webhook authenticator's log.

What are the following argument for: --authentication-kubeconfig, --authorization-kubeconfig, --kubeconfig? Are they all used for communicating with kube-apiserver? What's the effect if none of them is provided? 

One of difficulties I have is that I need to make gardener webhook authenticator ready to start before I have kube-apiserver. That means if the values for --authentication-kubeconfig, --authorization-kubeconfig, --kubeconfig are kubeconfig files to contact kube-apiserver, I don't have them before kube-apiserver starts. I don't have the IP address and port. I don't have the CA certificate either.

If I use a client.crt/key that is available on control plane node, e.g. apiserver-kubelet-client.crt/key, would it work and/or is recommended?

**Comment by jianhang33** [comment]
using apiserver-kubelet-client.crt/key for client.crt/key worked. Based on the usage of client.crt/key you described, it seems logical to use the certificates on control plane nodes, which I believe are signed by the kube-apiserver's CA, but I am wondering what your thought is.

**Comment by dimityrmirchev** [comment]
Hi @jianhang33 

--authentication-kubeconfig, --authorization-kubeconfig are the kubeconfigs used for delegating authentication and authorization to the targeted `kube-apiserver`. They are used in order for OWA to determine if the caller has rights to access paths such as `/validate-token`, `/metrics` or others. Naturally if these kubeconfigs point to `kube-apiserver` A the credentials that are used to query the `/validate-token` should be issued by `kube-apiserver` A. This verification may not always be needed (depending on the use case). If you want to skip it then you can pass `--kubeconfig` without any user info in it. Then the caller will be authenticated as `anonymous`.

The --kubeconfig is the cluster that OWA reads its `openidconnects` from. If some of these kubeconfigs is not set then in-cluster kubeconfig will be used.


> That means if the values for --authentication-kubeconfig, --authorization-kubeconfig, --kubeconfig are kubeconfig files to contact kube-apiserver, I don't have them before kube-apiserver starts. I don't have the IP address and port. I don't have the CA certificate either.

Why do you need to start the webhook before the kube-apiserver? Can't you do the opposite?

> If I use a client.crt/key that is available on control plane node, e.g. apiserver-kubelet-client.crt/key, would it work and/or is recommended?

Depending on the use case you can generate client certificate for this sole purpose (should be issued by the kube-apiserver's CA) or you can omit the credentials.

**Comment by jianhang33** [comment]
Thanks @dimityrmirchev for your answer. It helps a lot, and I wish them to be in docs in the future. Based on your answer, it doesn't look I need to make any changes.

Deployment of the webhook is done immediately after the cluster is up and is part of an automated process, therefore I need have all necessary information before hand.

> Depending on the use case you can generate client certificate for this sole purpose (should be issued by the kube-apiserver's CA) or you can omit the credentials.

By "omit the credentials", do you mean leaving the fields "client-certificate" and "client-key" empty in the webhook config file assigned to "authentication-token-webhook-config-file"?

**Comment by dimityrmirchev** [comment]
> By "omit the credentials", do you mean leaving the fields "client-certificate" and "client-key" empty in the webhook config file assigned to "authentication-token-webhook-config-file"?

Yes, if there is no need for the `kube-apiserver` to authenticate against the OWA (for example in a setup where OWA is in the internal network and traffic is trusted + restricted with network policies) then you can skip these credentials. If you do this you can see errors similar to "forbidden system:anonymous is not allowed to post to /validate-token". To fix this you can add the "/validate-token" path to the always allowed list [here](https://github.com/gardener/oidc-webhook-authenticator/blob/e0b023fd994d76c88aefc07db60f1cb20f282a14/charts/oidc-webhook-authenticator/values.yaml#L66)

**Comment by jianhang33** [comment]
Thanks. I have tried it and it worked.
