### ISSUE TITLE
Migrate to go-jose/go-jose

### ISSUE THREAD

**Issue by dimityrmirchev** [gardener/oidc-webhook-authenticator#161]
**What would you like to be added**:
`gopkg.in/square/go-jose.v2` is archived and should be replaced with https://github.com/go-jose/go-jose

**Why is this needed**:
`gopkg.in/square/go-jose` is not supported.

**Comment by SAMBILI** [comment]
maybe this will help
https://bit.ly/3TzaAQd
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)
