### ISSUE TITLE
Installing the webhook authenticator results in RBAC error

### ISSUE THREAD

**Issue by dimityrmirchev** [gardener/oidc-webhook-authenticator#42]
**What happened**:
```
I1028 13:03:28.807485       1 oidc.go:273] OIDC: No x509 certificates provided, will use host's root CA set
2021-10-28T13:03:28.807Z	INFO	controllers.OpenIDConnect	Reconcile finished	{"openidconnect": "dex"}
E1028 13:03:46.583351       1 webhook.go:202] Failed to make webhook authorizer request: subjectaccessreviews.authorization.k8s.io is forbidden: User "system:serviceaccount:default:oidc-webhook-authenticator" cannot create resource "subjectaccessreviews" in API group "authorization.k8s.io" at the cluster scope
E1028 13:03:46.583395       1 errors.go:77] subjectaccessreviews.authorization.k8s.io is forbidden: User "system:serviceaccount:default:oidc-webhook-authenticator" cannot create resource "subjectaccessreviews" in API group "authorization.k8s.io" at the cluster scope
E1028 13:04:06.580685       1 webhook.go:202] Failed to make webhook authorizer request: subjectaccessreviews.authorization.k8s.io is forbidden: User "system:serviceaccount:default:oidc-webhook-authenticator" cannot create resource "subjectaccessreviews" in API group "authorization.k8s.io" at the cluster scope
E1028 13:04:06.580712       1 errors.go:77] subjectaccessreviews.authorization.k8s.io is forbidden: User "system:serviceaccount:default:oidc-webhook-authenticator" cannot create resource "subjectaccessreviews" in API group "authorization.k8s.io" at the cluster scope
E1028 13:04:26.584872       1 webhook.go:202] Failed to make webhook authorizer request: subjectaccessreviews.authorization.k8s.io is forbidden: User "system:serviceaccount:default:oidc-webhook-authenticator" cannot create resource "subjectaccessreviews" in API group "authorization.k8s.io" at the cluster scope
E1028 13:04:26.584907       1 errors.go:77] subjectaccessreviews.authorization.k8s.io is forbidden: User "system:serviceaccount:default:oidc-webhook-authenticator" cannot create resource "subjectaccessreviews" in API group "authorization.k8s.io" at the cluster scope

```

/cc @caulagi

I opened an issue so we can better track the progress. I will update this issue with a sample configuration for installation.

**Comment by caulagi** [comment]
@dimityrmirchev thanks for the quick fix and responses. I am away for a few days. I will get back/confirm next week.

**Comment by caulagi** [comment]
@dimityrmirchev I can confirm that the example you provided in https://github.com/gardener/oidc-webhook-authenticator/issues/42#issuecomment-954674706 works for me. However, I have 2 followup questions - 

* Is the plan to remove `webhookConfig`? The helm charts under `helm` directory seems to use self-signed certificates created by cert-manager. That seems a better approach or? I can't commit the current yaml I have as is since it has the private key in plain text.

* Is it possible to install in a separate namespace (not `default`). I tried but it seems like there are references to `default` that cannot be configured right now. I can probably make a PR for this.

**Comment by dimityrmirchev** [comment]
@caulagi I am glad that you got it working. The chart under `helm` directory seems to have some issues one of which is that the the deployment of the `oidc-webhook-authenticator` is always installed in the `default` namespace ([ref](https://github.com/gardener/oidc-webhook-authenticator/blob/74b8b956ef101750cba313a98e9829d57c3d690c/helm/oidc-webhook-authenticator/templates/deployment.yaml#L4)). Since we do not want to maintain two separate charts I will delete the chart under the `helm` directory in the next couple of days. I see your point that you do not want to commit a private key, but the chart itself does not require you to do so. You can fetch the key from a safe key storage and use it only during the deployment. I can provide an alternative to `webhookConfig` via `cert-manager` so that `webhookConfig` will not be mandatory if `cert-manager` is enabled. Please tell me if this will suit your needs and I can issue a PR in the next couple of days.

**Comment by caulagi** [comment]
Yes, that would be great. We want to install the chart in a separate namespace and use `cert-manager` for providing the secrets in that namespace.

**Comment by dimityrmirchev** [comment]
@caulagi I opened a PR #51 
You can enable `cert-manager` by setting `webhookConfig.certificates.certManager.enabled: true`. Regarding my previous comment the `caBundle` for the `validatingwebhookconfiguration` is injected via [ca-injector](https://cert-manager.io/docs/concepts/ca-injector/) so that no manual work is required on your side. Mind that as a prerequisite you need `cert-manager` installed in the cluster. Also since this PR is not yet merged changes may occur.

You can install the authenticator in your desired namespace by running something like 
`helm upgrade --install --namespace my-desired-namespace oidc-webhook-authenticator ./charts/oidc-webhook-authenticator`

**Comment by caulagi** [comment]
@dimityrmirchev thanks for your help. I don't have RBAC errors anymore and we can close this.

**Comment by dimityrmirchev** [comment]
Closing as it is now resolved.
